CREATE DATABASE QLHANG
GO
USE QLHANG
GO
CREATE TABLE VATTU (
	MAVT CHAR(4) PRIMARY KEY,
	TENVT NVARCHAR(20),
	DVTINH NVARCHAR(20),
	SLCON INT
)
GO

CREATE TABLE HDBAN (
	MAHD VARCHAR(10) PRIMARY KEY,
	NGAYXUAT SMALLDATETIME,
	HOTENKHACH NVARCHAR(20)
)
GO

CREATE TABLE HANGXUAT(
	MAHD VARCHAR(10),
	MAVT CHAR(4),
	DONGIA MONEY,
	SLBAN INT,
	CONSTRAINT pk_hx PRIMARY KEY(MAHD, MAVT)
)
GO

INSERT INTO VATTU(MAVT,TENVT,DVTINH,SLCON) VALUES(N'VT01', N'XI MANG', 'VND', 100)
INSERT INTO VATTU(MAVT,TENVT,DVTINH,SLCON) VALUES(N'VT02', N'CAT', 'VND', 200)
INSERT INTO HDBAN(MAHD,NGAYXUAT,HOTENKHACH) VALUES(N'HD001',CAST(N'2022-5-10'AS DATE),N'BUI XUAN HOANG')
INSERT INTO HDBAN(MAHD,NGAYXUAT,HOTENKHACH) VALUES(N'HD005',CAST(N'2022-9-10'AS DATE),N'HOANG CONG SON')
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD001',N'VT01',100000, 150)
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD002',N'VT01',200000, 300)
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD003',N'VT02',300000, 250)
INSERT INTO HANGXUAT(MAHD,MAVT,DONGIA,SLBAN) VALUES(N'HD004',N'VT02',100000, 100)

--QUERY
--cau2
SELECT TOP 1
MAHD, SUM(SLBAN * DONGIA) AS N'Tổng Tiền'
FROM HANGXUAT
GROUP BY MAHD
ORDER BY SUM(SLBAN * DONGIA) Desc;
--cau3
CREATE FUNCTION C3 
(@MAHD varchar(10))
RETURNS TABLE
AS
RETURN
    SELECT 
        HX.MAHD,
        HD.NGAYXUAT,
        HX.MAVT,
        HX.DONGIA,
        HX.SLBAN,  
        CASE
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Monday' THEN N'Thứ hai'            
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Tuesday' THEN N'Thứ ba'
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Wednesday' THEN N'Thứ tư'
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Thursday' THEN N'Thứ năm'
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Friday' THEN N'Thứ sáu'
            WHEN DATENAME(dw,HD.NGAYXUAT) = 'Saturday' THEN N'Thứ bảy'
            ELSE N'Chủ nhật'
        END AS NGAYTHU
    FROM HANGXUAT HX
    INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
    WHERE HX.MAHD = @MAHD;
--cau4
CREATE PROCEDURE c4 
@thang int, @nam int 
AS
SELECT 
SUM(SLBAN * DONGIA)
FROM HANGXUAT HX
INNER JOIN HDBAN HD ON HX.MAHD = HD.MAHD
where MONTH(HD.NGAYXUAT) = @THANG AND YEAR(HD.NGAYXUAT) = @NAM;